# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Hello, World.
description: >- # this means to ignore newlines until "baseurl:"
        Welcome to my personal page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: UA-141671152-1
repo: http://github.com/zhongxuank/zhongxuank.github.io
disqus_shortname: "zhongxuank"
disqus_site_shortname: "zhongxuank"

# Author Settings
author:
  name: Zhong Xuan Khwa
  job: Undergraduate Student
  bio: "Finishing my BSc in Yale-NUS College Singapore, deeply interested in Natural Language Processing and Graph Theory."
  thumb: /images/author.jpg
  email: zxkhwa@hotmail.com
  url: zhongxuank.github.io
  github: https://github.com/zhongxuank
  twitter: https://twitter.com/zhongxuank
  facebook: https://facebook.com/zhongxuan
  linkedin: https://linkedin.com/in/zhongxuan95


# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
